# Generated by Django 5.0 on 2026-04-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table='brands',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menus',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='sku',
            table='product_skus',
        ),
        migrations.AlterModelTable(
            name='skuimage',
            table='sku_images',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='subcategories',
        ),
    ]
