# Generated by Django 5.0 on 2026-04-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='expired_at',
            new_name='expires_at',
        ),
    ]
